In [14]:
import pandas as pd
import numpy as np

In [16]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep ="\t")
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
chipo.info

<bound method DataFrame.info of       order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]>

In [19]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [20]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [21]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [22]:
chipo.items

<bound method DataFrame.items of       order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]>

In [29]:
arr = chipo.groupby('item_name')
arr
arr = arr.sum()
# arr = arr.sort_values(['quantity'],ascending=False)
# arr.head(5)

In [24]:
# arr.columns
arr = chipo.groupby('choice_description')
arr = arr.sum()
arr = arr.sort_values(['quantity'],ascending=False)
arr.head(5)

                                                    order_id  quantity
choice_description
[Diet Coke]                                           123455       159
[Coke]                                                122752       143
[Sprite]                                               80426        89
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     43088        49
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     36041        42

In [25]:
ab = chipo.quantity.sum()
ab

4972

In [12]:
chipo.columns
chipo.item_price.dtype

dtype('O')

In [13]:
bb = lambda i: float(i[1:-1])
chipo.item_price = chipo.item_price.apply(bb)

In [ ]:
chipo.item_price.dtype

dtype('float64')

In [ ]:
aa = (chipo.quantity * chipo.item_price).sum()
cc = str(np.round(aa,2))
cc

'39237.02'

In [ ]:
chipo.columns
dd = chipo.order_id.value_counts().count()
dd

1834

In [ ]:
chipo.groupby(['order_id']).sum()

In [ ]:
chipo.columns
chipo.item_name.value_counts().count()

EXERCISE_3

In [30]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep="|",index_col='user_id')
users.head(25)
# users.tail(10)
# users.shape[0]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [31]:
users.shape[0]

943

In [32]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [33]:
# 8-savol:Ma'lumotlar to'plamidagi ustunlar soni qancha?
users.shape[1]

4

In [34]:
# 9-Savol:Ma'lumotlar to'plami qanday indekslanadi?
users.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

In [36]:
# 10-savol:Har bir ustunning ma'lumotlar turi qanday?
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [38]:
# 11-savol:Faqat 'occupation' ustunini chop eting.
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [39]:
# 12-savol:Ushbu ma'lumotlar to'plamida nechta turli kasblar mavjud?
users.occupation.nunique()  #kasblarni nomini 'unique' orqali chqarsa boladi.

21

In [40]:
# 13-savol:Eng tez-tez uchraydigan kasb nima?
users.occupation.value_counts().head(5)

student          196
other            105
educator          95
administrator     79
engineer          67
Name: occupation, dtype: int64

In [41]:
# 14-DataFrame-ni umumlashtiring.
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [42]:
# 15-savol:Barcha ustunlarni umumlashtiring
users.describe(include = 'all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [44]:
# 16-savol:Faqat 'occupation' ustunini umumlashtiring
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [45]:
# 17-savol:Foydalanuvchilarning o'rtacha yoshi qancha?
users['age'].mean()

34.05196182396607

In [46]:
# 18-savol:Eng kam uchraydigan yosh qaysi?
users['age'].value_counts().tail()

7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64

Exaercise_3

In [47]:
# 3-savol:Datani read qilib oling.
food = pd.read_csv('/content/drive/MyDrive/en.openfoodfacts.org.products.tsv',sep = "\t")
food

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356022,99567453,http://world-en.openfoodfacts.org/product/9956...,usda-ndb-import,1489059076,2017-03-09T11:31:16Z,1491244499,2017-04-03T18:34:59Z,"Mint Melange Tea A Blend Of Peppermint, Lemon ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
356023,9970229501521,http://world-en.openfoodfacts.org/product/9970...,tomato,1422099377,2015-01-24T11:36:17Z,1491244499,2017-04-03T18:34:59Z,乐吧泡菜味薯片,Leba pickle flavor potato chips,50 g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356024,9977471758307,http://world-en.openfoodfacts.org/product/9977...,openfoodfacts-contributors,1497018549,2017-06-09T14:29:09Z,1500730305,2017-07-22T13:31:45Z,Biscottes bio,NaN,300g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356025,9980282863788,http://world-en.openfoodfacts.org/product/9980...,openfoodfacts-contributors,1492340089,2017-04-16T10:54:49Z,1492340089,2017-04-16T10:54:49Z,Tomates aux Vermicelles,NaN,67g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356026,999990026839,http://world-en.openfoodfacts.org/product/9999...,usda-ndb-import,1489072709,2017-03-09T15:18:29Z,1491244499,2017-04-03T18:34:59Z,"Sugar Free Drink Mix, Peach Tea",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 4-savol:Birinchi 5 ta yozuvga qarang
food.head(20)

In [ ]:
# /5-savol:Ma'lumotlar to'plamidagi kuzatuvlar soni qancha?
food.shape
food.shape[0]

In [ ]:
# 6-savol:Ma'lumotlar to'plamidagi ustunlar soni qancha?
print(food.shape)
print(food.shape[1])
food.info()

In [ ]:
# 7-savol:Barcha ustunlar nomini chop eting.
food.columns

In [ ]:
# 8-savol:105-ustunning nomi nima?
food.columns[104]

In [ ]:
# 9-savol:105-ustun kuzatuvlarining turi qanday?
food.dtypes["-glucose_100g"]

In [ ]:
# 10-savol:Ma'lumotlar to'plami qanday indekslanadi?
food.index

In [ ]:
# 11-savol:19-kuzatuv mahsulotining nomi nima?
food.values[18][7]

Chipolite

In [ ]:
# 2-savol:Ushbu manzildan ma'lumotlar to'plamini import qiling.
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep = "\t")
chipo.head()

In [ ]:
# 2-savol:Ushbu manzildan ma'lumotlar to'plamini import qiling.
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep = "\t")
# 4-savol:Qancha mahsulot narxi 10,00 dollardan oshadi?
narx =[float(value[1:-1])for value in chipo.item_price]
chipo.item_price=narx
filtered = chipo.drop_duplicates(["item_name","quantity","choice_description"])
chippo = filtered[filtered.quantity==1]
ppp = chippo.query("item_price > 10")
ppp.head(30)

In [ ]:
# 5-savol:Har bir buyumning narxi qancha?
chipo[(chipo["item_name"]=="Nantucket Nectar") & chipo["quantity"]==1]

In [ ]:
# 6-savol:Element nomi bo'yicha tartiblang
chipo.sort_values(by="item_name")

In [ ]:
# 7-savol:Buyurtma qilingan eng qimmat buyumning miqdori qancha edi?
chipo.sort_values(by="item_price",ascending=False).head(1)

In [ ]:
# 8-savol:Sabzavotli salat idishiga necha marta buyurtma berilgan?
savat =chipo[chipo["item_name"]=="Veggie Salad Bowl"]
len(savat)

In [ ]:
# 9-savol:Kimdir bir nechta konservalangan gazlangan suvga necha marta buyurtma bergan?
suv = chipo[(chipo["item_name"]=="Canned Soda") & chipo["quantity"]==1]
len(suv)

In [ ]:
# OCCUPATION

In [ ]:
# 2-savol:Ushbu manzildan ma'lumotlar to'plamini import qiling.
import pandas as pd
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep="|")
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [ ]:
# 3-savol:Uni foydalanuvchilar deb nomlangan o'zgaruvchiga tayinlang va indeks sifatida "user_id" dan foydalaning
index_col='user_id'

In [ ]:
# 4-savol:Birinchi 25 ta yozuvni ko'ring
users.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

In [ ]:
# 5-savol:Oxirgi 10 ta yozuvga qarang
users.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

In [ ]:
# 6-savol:Ma'lumotlar to'plamidagi kuzatuvlar soni qancha?
users.shape[0]

943

In [ ]:
# 7-savol:Ma'lumotlar to'plamidagi ustunlar soni qancha?
users.shape[1]

5

In [ ]:
# 8-savol:Barcha ustunlar nomini chop eting.
users.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [ ]:
# 9-savol:Ma'lumotlar to'plami qanday indekslanadi?
users.index

RangeIndex(start=0, stop=943, step=1)

In [ ]:

# 10-savol:Har bir ustunning ma'lumotlar turi qanday?
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [ ]:
# 11-savol:Faqat kasb ustunini chop eting.
users.occupation
users['occupation'].head(10)

0       technician
1            other
2           writer
3       technician
4            other
5        executive
6    administrator
7    administrator
8          student
9           lawyer
Name: occupation, dtype: object

In [ ]:
# 12-savol:Ushbu ma'lumotlar to'plamida nechta turli kasblar mavjud?
users.occupation.nunique()

21

In [ ]:
# 13-savol:Eng tez-tez uchraydigan kasb nima?
users.occupation.value_counts().head(1).index[0]

'student'

In [ ]:
# 14-savol:DataFrame-ni umumlashtiring.
users.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [ ]:
# 15-savol:Barcha ustunlarni umumlashtiring
users.describe(include="all")

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

In [ ]:
# 16-savol:Faqat kasb ustunini umumlashtiring
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [ ]:
# 17-savol:Foydalanuvchilarning o'rtacha yoshi qancha?
round(users.age.mean())

34

In [ ]:
# 18-savol:Eng kam uchraydigan yosh qaysi?
users.age.value_counts().tail()

7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64